version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: fast_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  email:
    image: mailhog/mailhog
    ports:
        - "1025:1025"
        - "8025:8025"