"""contacts new7

Revision ID: 1c48b68c7f37
Revises: 1f2a62d82596
Create Date: 2024-12-15 22:14:34.511935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c48b68c7f37'
down_revision: Union[str, None] = '1f2a62d82596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_mod', 'expired_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_mod', 'expired_at',
               existing_type=sa.String(length=255),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
