"""contacts new2

Revision ID: d121f14da2c5
Revises: 7ab7bd5087e9
Create Date: 2024-12-15 20:59:17.697003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd121f14da2c5'
down_revision: Union[str, None] = '7ab7bd5087e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts_mod', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts_mod', 'created_at')
    # ### end Alembic commands ###
